### ISSUE TITLE
Logout function problem + Background image bug?

### ISSUE THREAD

**Issue by scottjsh** [RetherSzu/valorant-daily-shop#2]
https://github.com/RetherSzu/valorant-daily-shop/assets/62782800/ad19ecbc-75e9-421b-871f-80e73a34625b

I can't log out with the logout button. And even though I didn't check 'Stay sign in', if I press the logout button and log in with another account, I automatically continue to log in with my old account.

+ I think the background image behind Outlaw looks weird.

**Comment by scottjsh** [comment]
> I can't log out with the logout button. And even though I didn't check 'Stay sign in', if I press the logout button and log in with another account, I automatically continue to log in with my old account.

I was wrong.
The app always keep signed in.

**Comment by RetherSzu** [comment]
Hello @scottjsh 

I tried to solve the disconnection problem without success, so I opened an issue on the GitHub repository of the API I use.

Issue: [link](https://github.com/techchrism/valorant-api-docs/issues/58)

and thank you for your feedback

**Comment by RetherSzu** [comment]
Hello @scottjsh ,

Thank you for your patience. I wanted to follow up on the logout problem. I'm pleased to inform you that the issue has been resolved in the [Latest Release](https://github.com/RetherSzu/valorant-daily-shop/releases/tag/v1.3) of the app.

If you experience any further issues or have additional feedback, please don't hesitate to let me know.

Thank you again for your valuable feedback and support.
