### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by scottjsh** [RetherSzu/valorant-daily-shop#3]
It may be too early, but I'd like to ask you to create a tab where app users can see the skins they have.
I'm sorry compared to other apps, but the following is an example of an app called Statics.
You can click on each gun, and when you click on each gun, it shows the skin that it has.
(Statics can even equip skin, but bugs often occur and it seems to be a little useless feature.)

<img src="https://github.com/RetherSzu/valorant-daily-shop/assets/62782800/554ce159-510c-423e-93cd-daed77c82ecb" width="400px">

**Comment by scottjsh** [comment]
Plus Statics are not aligned.

**Comment by RetherSzu** [comment]
Hi @scottjsh ,

Thank you for your suggestion! I will be adding this new feature in the next update and am already working on it.

Thanks again for your feedback!

**Comment by RetherSzu** [comment]
Hey @scottjsh,

Thanks for your feedback and request for a player loadout management feature!

It's now available in our [latest version!](https://github.com/RetherSzu/valorant-daily-shop/releases/tag/v1.3)
